# Generated by Django 5.2.7 on 2025-10-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('author', models.CharField()),
                ('isbn', models.CharField(max_length=17)),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price_local', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock_quantity', models.IntegerField()),
                ('category', models.CharField()),
                ('supplier_country', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
