# Generated by Django 5.2.7 on 2025-10-18 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_options_alter_book_cost_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost_usd',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='selling_price_local',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='supplier_country',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
    ]
